### PR TITLE
fix(android/application): org.nativescript.widgets.Utils::getDrawable

### LINKED ISSUE #9562: Calling js method onConfigurationChanged failed - Error: java.lang.StringIndexOutOfBoundsException
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.1.2
 - Cross-platform modules: 8.1.3
 - Android Runtime: 8.1.1
 - iOS Runtime: N/A
 - XCode Version: N/A
 - Plugin(s): Many (not relevant here)

**Describe the bug**

```
NativeScriptException

Calling js method onConfigurationChanged failed
Error: java.lang.StringIndexOutOfBoundsException: length=4; index=6
```

image

This bug probably happens because I may have a `null` src somewhere on an image. 

In my app, I only use distant images (on a server) with Image component, except two background-image with a static path:

```css
background-image: url("res://background");
background-image: url("res://watermark");
```

i don't think these static paths cause the problem. I am getting the report in Sentry so I don't really know what causes the problem.

**To Reproduce**

?

**Expected behavior**

NativeScript should not throw an exception but should show a log for this problem.

**Sample project**

I don't have a reproduction scenario actually

**Additional context**

I am actually making a PR which possibly fixes the issue.

### PR DESCRIPTION
**Pull request by sebj54**
Avoid StringIndexOutOfBoundsException in org.nativescript.widgets.Utils

As it is my first PR to this repo, I am not experimented that much with native development. Feel free to guide me so I'll now next time :)

For example, I don't know how to test this file in a NativeScript project :/

## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

Calling org.nativescript.widgets.Utils::getDrawable with a uri shorter than 6 characters throws a StringIndexOutOfBoundsException.

## What is the new behavior?

An early check in this method ensures uri is longer than 6 characters so a warning is shown in the console.

Fixes #9562.

### CODE REVIEW

File: packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java [hunk 1]
```diff
@@ -36,8 +36,14 @@
 
 public class Utils {
 	public static Drawable getDrawable(String uri, Context context){
-		String resPath = uri.substring("res://".length());
-		int resId = context.getResources().getIdentifier(resPath, "drawable", context.getPackageName());
+		int resId = 0;
+		int resPrefixLength = "res://".length();
+		
+		if (uri.length() >= resPrefixLength) {
```
Comment (rigor789) [inline packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java:42]: I think we may want the check to be `>` since `>=` would make `restPath` an empty string in case the `uri` is `res://`

```suggestion
		if (uri.length() > resPrefixLength) {
```

**Comment by rigor789** [comment]
@sebj54 thanks for taking the time to do a PR - the change look good to me, I left a minor suggestion in the review.

The way you can test this requires building the widgets, which can be done by running `npm start` ([after setting up the repo](https://github.com/NativeScript/NativeScript#contribute)) and selecting the `@nativescript/ui-mobile-base: Build for npm` option - this should build the widgets lib. Then you can run any of the test apps in the repo: ui, automated or toolbox.

For this case specifically, I think a new test-case in the `ui` app would suffice - adding a few views and setting their `background-image` to a few variants like `res://` `res://non-existent` `res://icon`

File: packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java (hunk 1 above)
Comment (sebj54) [reply packages/ui-mobile-base/android/widgets/src/main/java/org/nativescript/widgets/Utils.java:42]: You're right, it will be more performant like this. No need to try to load an empty path!

**Comment by sebj54** [comment]
@rigor789 Thank you for your help! I added some views in the `ui` app. It runs correctly on my device but feel free to let me know if it's not exactly what was expected.

PS: The Android CI test has failed, is it expected?

**Review by NathanWalker — DISMISSED** [review]

**Review by rigor789 — APPROVED** [review]

**Comment by rigor789** [comment]
@sebj54 yeah, the CI has been flaky for some time now, still not sure why - it works locally... 

I added a few more test-cases - the last few make the app crash without the fix, so they verify that this fixes the IndexOutOfBoundsException. 

Awesome job 🎉

**Comment by sebj54** [comment]
Thanks for the time you took to get me ready :)
So happy to have one commit in such an awesome project! 🙌

**Comment by rigor789** [comment]
Thanks for taking the time @sebj54, hopefully sparked some interest in contributing again in the future 🎉

**Comment by sebj54** [comment]
I hope to be able to do it soon :)
