### PR TITLE
fix(ios) Navigation via swipe leads to crash

### LINKED ISSUE #9096: Navigation via swipe leads to crash of iOs app
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):

- Nativescript 7.0.11, @nativescript/core 7.0.13, @nativescript/ios 7.0.6, @nativescript/android is not installed.
 - Android Runtime: n/A
 - iOS Runtime: iPhone 7, iOS 14.0.1 (real iPhone, no simulator)
 - XCode Version: 12.2

```
    "dependencies": {
        "@angular/animations": "~11.0.0",
        "@angular/common": "~11.0.0",
        "@angular/compiler": "~11.0.0",
        "@angular/core": "~11.0.0",
        "@angular/forms": "~11.0.0",
        "@angular/platform-browser": "~11.0.0",
        "@angular/platform-browser-dynamic": "~11.0.0",
        "@angular/router": "~11.0.0",
        "@nativescript/angular": "11.0.0",
        "@nativescript/core": "~7.0.0",
        "@nativescript/secure-storage": "^3.0.0",
        "@nativescript/theme": "~2.3.0",
        "ajv": "^6.10.2",
        "json2typescript": "^1.4.1",
        "lodash": "^4.17.15",
        "nativescript-keyboard-toolbar": "^1.1.0",
        "nativescript-theme-core": "~2.0.24",
        "nativescript-ui-dataform": "~7.0.0",
        "nativescript-ui-sidedrawer": "~9.0.0",
        "nativescript-webview-interface": "^1.4.4",
        "reflect-metadata": "~0.1.12",
        "rxjs": "^6.6.0",
        "zone.js": "~0.11.1"
    },
    "devDependencies": {
        "@angular/compiler-cli": "~11.0.0",
        "@nativescript/ios": "7.0.6",
        "@nativescript/webpack": "~3.0.0",
        "@ngtools/webpack": "~11.0.0",
        "typescript": "~4.0.0"
    },
    "main": "main.js"
```

**Describe the bug**
I receive a runtime error (which causes the iOS app to crash), when I initiate a swipe right that should lead the user back to a previouse route.

Here's the logs from XCode:
```
2020-12-13 23:35:38.843480+0100 medlongplaybeta[682:92427] CONSOLE LOG: Angular is running in development mode. Call enableProdMode() to enable production mode.
2020-12-13 23:36:07.923949+0100 medlongplaybeta[682:92427] ***** Fatal JavaScript exception - application has been terminated. *****
2020-12-13 23:36:07.924162+0100 medlongplaybeta[682:92427] NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'frame' of null
 at 
	_removeEntry(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122200:28)
	at _updateBackstack(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122274:18)
	at setCurrent(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122792:18)
	at push.../node_modules/@nativescript/core/ui/page/index.js.UIViewControllerImpl.viewDidAppear(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:130539:19)
2020-12-13 23:36:07.926845+0100 medlongplaybeta[682:92427] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'frame' of null
 at 
	_removeEntry(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122200:28)
	at _updateBackstack(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122274:18)
	at setCurrent(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122792:18)
	at push.../node_modules/@nativescript/core/ui/page/index.js.UIViewControllerImpl.viewDidAppear(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:130539:19)
', reason: '(null)'
*** First throw call stack:
(0x18c289114 0x19faafcb4 0x101ae00e4 0x101e964f0 0x101e96354 0x101dab08c 0x101ce0828 0x101cdfe60 0x101b5ae18 0x1019df6a8 0x101b2ac94 0x101b2c1b4 0x18e410858 0x18e4111b8 0x18e4114b8 0x18e34be70 0x18e341b1c 0x18e4334d8 0x18e44891c 0x18efc1ec0 0x18ef96578 0x18ef96a80 0x18ef96bd0 0x18f4e05a8 0x102bb95fc 0x102bc7a6c 0x18c208c30 0x18c2030e8 0x18c202200 0x1a22fd598 0x18eac8004 0x18eacd5d8 0x101b2c044 0x101b2a4f8 0x101a9e5dc 0x101a41160 0x101adaea4 0x101ad4f68 0x100f8f750 0x18bee1598)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'frame' of null
 at 
	_removeEntry(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122200:28)
	at _updateBackstack(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122274:18)
	at setCurrent(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:122792:18)
	at push.../node_modules/@nativescript/core/ui/page/index.js.UIViewControllerImpl.viewDidAppear(file:///var/containers/Bundle/Application/2D36BDC5-949C-47B2-A658-58A106FFD707/medlongplaybeta.app/app/vendor.js:130539:19)
', reason: '(null)'
terminating with uncaught exception of type NSException

```

**To Reproduce**
component.html:
```
<StackLayout class="page" (swipe)="onSwipe($event)">
....
</StackLayout>
```

component.ts: 
```
@Component({
    selector: "app-component",
    moduleId: module.id,
    templateUrl: "./component.html"
})
export class ComponentTest {
    constructor(
        public navigationService: NavigationService,
    ) {}

    onSwipe(args: SwipeGestureEventData): void {
        if (args.direction === SwipeDirection.right) {
            this.navigationService.navigateBack(this.routeBack);
        }
    }
```

navigation.service.ts: 
```
@Injectable({ providedIn: "root" })
export class NavigationService {
    constructor(private ngZone: NgZone, private routerExtensions: RouterExtensions) {}

    navigateBack(routeBack: string) {
        this.ngZone.run(() =>
            this.routerExtensions.navigate([routeBack], {
                clearHistory: true,
                transition: {
                    name: "slideRight"
                }
            })
        );
    }
```

**Expected behavior**
The app should not crash.

Thanks for your help!

### PR DESCRIPTION
**Pull request by gabrielbiga**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?
Sometimes the application crashes when the user back the page with iOS back swipe.

## What is the new behavior?
This commit adds a new check to verify if the new page is available before checking the frame.
It seems to fix random crashes when navigating on iOS device.

Fixes #9096

### CODE REVIEW

File: packages/core/ui/frame/frame-common.ts [hunk 1]
```diff
@@ -236,7 +236,7 @@ export class FrameBase extends CustomLayoutView {
 		const newPage = entry.resolvedPage;
 		// In case we navigated forward to a page that was in the backstack
 		// with clearHistory: true
-		if (!newPage.frame) {
+		if (newPage && !newPage.frame) {
```
Comment (rigor789) [inline packages/core/ui/frame/frame-common.ts:239]:
```suggestion
		if (!newPage?.frame) {
```

**Review by NathanWalker — APPROVED** [review]
