### PR TITLE
setItem event fixed

### LINKED ISSUE #1142: ObservableArray does not provide removed items through EventData when an UPDATE action occurs
Here's a snippet from ObservableArray.js:

```JavaScript
     ObservableArray.prototype.setItem = function (index, value) {
        this._array[index] = value;
        this.notify({
            eventName: CHANGE, object: this,
            action: ChangeType.Update,
            index: index,
            removed: new Array(1),
            addedCount: 1
        });
    };
```

The following line: `removed: new Array(1)` is the one I am talking about.

### PR DESCRIPTION
**Pull request by enchev**
Fixed #1142

### CODE REVIEW

**Comment by enchev** [comment]
run ci

**Comment by enchev** [comment]
run ci

**Comment by dtopuzov** [comment]
:+1:

File: apps/tests/observable-array-tests.ts [hunk 1]
```diff
@@ -567,7 +592,7 @@ export var test_ObservableArray_lastIndexOfShouldReturnCorrectIndex = function (
     var result = array.lastIndexOf("two");
     // ```
     // </snippet>
-   TKUnit.assert(result === 2, "ObservableArray lastIndexOf() should return correct index!");
+    TKUnit.assert(result === 2, "ObservableArray lastIndexOf() should return correct index!");
```
Comment (hdeshev) [inline apps/tests/observable-array-tests.ts]: Bad indentation

**Comment by hshristov** [comment]
:+1:

**Comment by ErjanGavalji** [comment]
:+1:

**Comment by nsndeck** [comment]
:+1:

File: apps/tests/observable-array-tests.ts [hunk 2]
```diff
@@ -85,6 +85,31 @@ export var test_ObservableArray_setItemShouldSetCorrectItem = function () {
     TKUnit.assert(array.getItem(1) === 5, "ObservableArray setItem() should set correct item!");
 };
 
+export var test_ObservableArray_setItemShouldRaiseCorrectEvent = function () {
+    // <snippet module="data/observable-array" title="observable-array">
+    // ### Set item at specified index using setItem(index, item) method and observe change event data.
+    // ``` JavaScript
+    var index : number;
```
Comment (hdeshev) [inline apps/tests/observable-array-tests.ts]: Extra space: `index:` instead of `index :`

File: apps/tests/observable-array-tests.ts [hunk 3]
```diff
@@ -85,6 +85,31 @@ export var test_ObservableArray_setItemShouldSetCorrectItem = function () {
...
+        addedCount = args.addedCount; // Number of added items. In this case 1.
+        removed = args.removed; // Array of removed items. In this case with single item (2).
+    });
+    array.setItem(1, 5);
+    // ```
+    // </snippet>
+    TKUnit.assertEqual(index, 1);
+    TKUnit.assertEqual(action, observableArrayModule.ChangeType.Update);
+    TKUnit.assertEqual(addedCount, 1);
+    TKUnit.assertEqual(removed[0], 2);
```
Comment (PanayotCankov) [inline apps/tests/observable-array-tests.ts]: Minor note: You may assert that removed.length === 1

**Comment by PanayotCankov** [comment]
:+1:
