### PR TITLE
fix(root-layout): Use isNumber to check for translate and scale values

### LINKED ISSUE #10289: RootLayout exitAnimations don't work when translate or scale values are set to 0
### Issue Description

When translate or scale values are set to 0 for exitTo field when animating rootLayout shade cover the animation doesn't work as intended.

### Reproduction

```js
getRootLayout().open(<a valid view object>, {
      shadeCover: {
        color: '#000',
        opacity: 0.7,
        tapToClose: true,
      },
      animation: {
        enterFrom: {
          scaleX: 0,
          scaleY: 0,
          duration: 300,
          curve: CoreTypes.AnimationCurve.easeInOut,
        },
        exitTo: {
          scaleY: 0,
          scaleX: 0,
          duration: 300,
          curve: CoreTypes.AnimationCurve.easeInOut,
        },
      },
    });
```

In this case, the entry animation scale works, but not the exit animation scale.

### Relevant log output (if applicable)

_No response_

### Environment

Tested on:
"@nativescript/core": "8.5.1",
"@nativescript/android": "8.5.0",
"@nativescript/ios": "8.4.1",

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/NativeScript/NativeScript/issues) as well as [StackOverflow](https://stackoverflow.com/questions/tagged/nativescript) and this has not been posted before
- [X] This is a bug report
- [X] I agree to follow this project's [Code of Conduct](https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#coc)

### PR DESCRIPTION
**Pull request by shiv19**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/tools/notes/DevelopmentWorkflow.md#running-unit-tests-application.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/tools/notes/WritingUnitTests.md.

## What is the current behavior?

When animating shadeCover for root layout, the exit animation doesn't work if translate or scale values are 0.

## What is the new behavior?

The exit animations work as intended when the translate or scale values are 0.

Fixes/Implements/Closes #10289.

### CODE REVIEW

File: packages/core/ui/layouts/root-layout/root-layout-common.ts [hunk 1]
```diff
@@ -382,8 +382,8 @@ export class RootLayoutBase extends GridLayout {
 			target: targetView,
 			...defaultTransitionAnimation,
 			...(exitTo || {}),
-			translate: { x: exitTo.translateX || defaultTransitionAnimation.translateX, y: exitTo.translateY || defaultTransitionAnimation.translateY },
-			scale: { x: exitTo.scaleX || defaultTransitionAnimation.scaleX, y: exitTo.scaleY || defaultTransitionAnimation.scaleY },
+			translate: { x: isNumber(exitTo.translateX) ? exitTo.translateX : defaultTransitionAnimation.translateX, y: isNumber(exitTo.translateY) ? exitTo.translateY : defaultTransitionAnimation.translateY },
+			scale: { x: isNumber(exitTo.scaleX) ? exitTo.scaleX : defaultTransitionAnimation.scaleX, y: isNumber(exitTo.scaleY) ? exitTo.scaleY : defaultTransitionAnimation.scaleY },
```
Comment (NathanWalker) [inline packages/core/ui/layouts/root-layout/root-layout-common.ts:386]: Very nice find @shiv19 - I believe you just need to import `isNumber` in this file.

**Review by NathanWalker — CHANGES_REQUESTED** [review]

**Review by NathanWalker — APPROVED** [review]
