### PR TITLE
fix(timer): setTimeout/setInterval support for boolean period

### LINKED ISSUE #7567: Different casting rules in setTimeout/setInterval in nativescript
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.2
 - Cross-platform modules:  6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime:
 - Plugin(s):

**Describe the bug**

Nativescript has different casting rules compared to browser javascript. (at least in timer.setTimeout and timer.setInterval functions).

**To Reproduce**

```
setTimeout(() => console.log("Hello"), false);
``` 
Fails in nativescript, but suceeds in js.

**Expected behavior**
Casting rules should be the same.

**Sample project**

**Additional context**

Many libraries out there are using code like 
```
setTimeout(callback, false);
```
which fails and is usually hard to debug. Was bitten by `redux-perist` lib.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/77415766-different-casting-rules-in-settimeout-setinterval-in-nativescript?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F12908224&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bundyo**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [x] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [x] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
setTimeout/setInterval can't be called with Boolean period.

## What is the new behavior?
setTimeout/setInterval can be called with a Boolean period - cast to either 0 or 1.

Fixes/Implements/Closes #7567.

### CODE REVIEW

File: tns-core-modules/timer/timer.d.ts [hunk 1]
```diff
@@ -9,7 +9,7 @@
  * @param milliseconds The time to wait before the function is called. Defaults to 0.
  * @param args One or more parameter to use once the function is called. Defaults to no parameters.
  */
-export function setTimeout(callback: Function, milliseconds?: number,  ...args: any[]): number;
+export function setTimeout(callback: Function, milliseconds?: number | boolean,  ...args: any[]): number;
```
Comment (vakrilov) [inline tns-core-modules/timer/timer.d.ts]: Don't update the typings.
It's ok to handle the case if accidentally pass the wrong type, but should not be "officially" in the type definitions.
For reference: [`lib.dom.d.ts`](https://github.com/microsoft/TypeScript/blob/34dd4b8da52b91e178b30d8e4f097f914b9ff472/lib/lib.dom.d.ts#L18235-L18236)

**Comment by vakrilov** [comment]
test
