### PR TITLE
fix(FormattedString) Allow Span descendants in FormattedString

### LINKED ISSUE #7369: Custom components extending Span are not rendered in FormattedString
**Environment**
5.4.2, probably all previous versions.

**Describe the bug**
Custom components extending Span are not rendered in FormattedString.

**To Reproduce**
1. Create a custom component that extends Span.
1. Add it inside FormattedString

**Expected behavior**
To see the custom component rendered

### PR DESCRIPTION
**Pull request by bundyo**
## PR Checklist

- [x] The PR title follows our guidelines: https://github.com/NativeScript/NativeScript/blob/master/CONTRIBUTING.md#commit-messages.
- [x] There is an issue for the bug/feature this PR is for. To avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it.
- [x] You have signed the [CLA](http://www.nativescript.org/cla).
- [ ] All existing tests are passing: https://github.com/NativeScript/NativeScript/blob/master/DevelopmentWorkflow.md#running-unit-tests.
- [ ] Tests for the changes are included - https://github.com/NativeScript/NativeScript/blob/master/WritingUnitTests.md.

## What is the current behavior?
Currently FormattedString doesn't allow custom components extending Span to be its children. This small PR fixes that.

## What is the new behavior?
It allows custom components extending Span.

Closes #7369.

### CODE REVIEW

**Comment by manoldonev** [comment]
test

File: tns-core-modules/text/formatted-string.ts [hunk 1]
```diff
@@ -95,7 +95,7 @@ export class FormattedString extends ViewBase implements FormattedStringDefiniti
     }
 
     public _addChildFromBuilder(name: string, value: any): void {
-        if (name === CHILD_SPAN) {
```
Comment (manoldonev) [inline tns-core-modules/text/formatted-string.ts]: Delete `CHILD_SPAN` constant as well as it is no longer used after this usage is eliminated.
